apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: weather-app-eap-cloud-ready
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
    app.openshift.io/runtime: eap
spec:
  replicas: 1
  selector:
    app: weather-app-eap-cloud-ready
    deploymentconfig: weather-app-eap-cloud-ready
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: weather-app-eap-cloud-ready
        deploymentconfig: weather-app-eap-cloud-ready
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          name: weather-app-eap-cloud-ready
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          env:
            - name: DB_DATABASE
              value: weather
            - name: DB_DRIVER
              value: postgresql
            - name: DB_JNDI
              value: 'java:jboss/datasources/WeatherDS'
            - name: DB_NONXA
              value: 'true'
            - name: DB_PASSWORD
              value: secret
            - name: DB_SERVICE_PREFIX_MAPPING
              value: weatherds-postgresql=DB
            - name: DB_URL
              value: >-
                jdbc:postgresql://$(WEATHER_POSTGRESQL_SERVICE_HOST):$(WEATHER_POSTGRESQL_SERVICE_PORT)/weather
            - name: DB_USERNAME
              value: mauro
            - name: JAEGER_AGENT_HOST
              value: $(JAEGER_ALL_IN_ONE_RHEL8_SERVICE_HOST)
            - name: JAEGER_AGENT_PORT
              value: $(JAEGER_ALL_IN_ONE_RHEL8_SERVICE_PORT_6831_UDP)
            - name: JAEGER_SAMPLER_PARAM
              value: '1'
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SERVICE_NAME
              value: weather-app-eap-cloud-ready
            - name: WILDFLY_TRACING_ENABLED
              value: 'true'
          image: >-
            image-registry.openshift-image-registry.svc:5000/redhat-jboss-eap-cloud-ready-demo/weather-app-eap-cloud-ready
---
kind: Service
apiVersion: v1
metadata:
  name: weather-app-eap-cloud-ready
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
spec:
  ports:
    - name: 9990-tcp
      protocol: TCP
      port: 9990
      targetPort: 9990
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  selector:
    app: weather-app-eap-cloud-ready
    deploymentconfig: weather-app-eap-cloud-ready
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: weather-app-eap-cloud-ready
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
spec:
  to:
    kind: Service
    name: weather-app-eap-cloud-ready
  port:
    targetPort: 8080
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: health
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
spec:
  path: /health
  to:
    kind: Service
    name: weather-app-eap-cloud-ready
  port:
    targetPort: 9990
  wildcardPolicy: None
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: metric
  namespace: redhat-jboss-eap-cloud-ready-demo
  labels:
    app: weather-app-eap-cloud-ready
spec:
  path: /metrics
  to:
    kind: Service
    name: weather-app-eap-cloud-ready
  port:
    targetPort: 9990
  wildcardPolicy: None




